name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: wenqiantay
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: wenqiantay/productivity:latest
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        env:
          RAILWAY_PROJECT_ID: 2018257b-e0ea-46bd-95e3-ddfe1a9157ff
          RAILWAY_SERVICE_ID: b4eb0dec-45bd-448a-a5c3-6928177df830
          RAILWAY_SERVICE_NAME: precious-celebration
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service ${{ env.RAILWAY_SERVICE_ID }} 